variables:
    APP_IMAGE: registry.2le.net/2le/2le:base-sf7-xdebug
    DB_SERVICE: registry.2le.net/2le/[PROJECT]:db
    DBTEST_SERVICE: registry.2le.net/2le/[PROJECT]:dbtest
    DEPLOY_HOST: cluster.2le.net
    DEPLOY_PATH: /data/docker/[PROJECT]-test/
    PROD_HOST: cluster.2le.net
    PROD_PATH: /data/docker/[PROJECT]/

include:
    - project: '2le/devops'
      ref: master
      file: '/gitlab-ci/symfony-pipeline.yml'
