services:
    dbtest:
        image: mariadb:lts
        environment:
            MARIADB_ROOT_PASSWORD: pass
            MARIADB_DATABASE: [PROJECT]

    symfony:
        build: .
        entrypoint: "/entrypoint_dev.sh"
        command: "frankenphp run --config /etc/caddy/Caddyfile"
        working_dir: /app
        ports:
            - "8[IDENTIFIER]:80"
        environment:
            - "COMPOSER_MEMORY_LIMIT=-1"
        depends_on:
            - dbtest
        volumes:
            - ./:/app/

    pma:
        image: phpmyadmin/phpmyadmin
        links:
            - dbtest:db
        ports:
            - "9[IDENTIFIER]:80"
        environment:
            UPLOAD_LIMIT: 3000000000
            PMA_HOST: dbtest
        depends_on:
            - dbtest
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
